const personTypes = [
      'male',
      'female',
      'homosexual',
      'lesbian',
      'catboy',
      'transexual',
      'bisexual',
      'femboy',
      'furry',
      'tomboy',
      'racist',
      'gamer',
      'clown',
      'gangsta',
      'discord mod',
      'moderator',
      'reddit mod',
      'twitter user',
      'twitch streamer',
      'programmer',
      '4chan user',
      'game developer',
      'homophobic',
      'transphobic',
      'weeb',
      'troller',
      'criminal',
      'pirate',
      'drug addict',
      'hacker',
      'exploiter',
      'meth addict',
      'speedrunner',
      'liberal',
      'autistic',
      'terrorist',
      'artist',
      'twitter artist',
      'president',
      'skinwalker',
      'prime minister',
      'youtuber',
      'nerd'
    ]

module.exports = {
  desc: "Returns a random job, gender or stereotype, I guess. (this is a crime against humanity)",
  func: function () {
    return personTypes[Math.floor(Math.random() * personTypes.length)]
  },
  array: personTypes,
  cmdconnected: 'cah'
}